### ISSUE TITLE
[Request] Usage of face masks

### ISSUE THREAD

**Issue by smanz** [apozas/contactdiary#18]
Alex,

thank you very much for this app, I use it on a daily basis for three weeks now.

I like that you focus on the essential features and resist to add bloat. This keeps the app clean and easy to use. 

Having said that, there is one feature I do miss, though. I'd like to note whether the people were wearing a face mask while I met them.
One might argue than this is somehow covered by the "did you keep distance" part.  Anyways, and this might be a matter of personal taste, I prefer to note this information separately.

For now, I use the notes field for that purpose. However, I think t would be more convenient to have a radio button for face masks.

Keep up the good work.

**Comment by apozas** [comment]
Hi smanz,

Thanks for the comment, it is very much appreciated. Although I myself try to always use a mask when outside home, I have my personal reservations for adding it as an input to the app. We had a similar discussion in #4, when in that case discussing adding the time of end of the contact. There, you can read

> I have had some thoughts about this. Asking for more information about the contacts is a bit tricky. The premise I use is that it must be a professional contact tracer who assesses whether a contact is risky enough, instead of the individual using the app. Adding too much information about a contact may incline to self-evaluation of contacts, and to thoughts of "well, this contact doesn't seem of enough risk, so I won't tell the contact tracer". That is part of the reason why, right now, there is no question about mask use, for example.

In the specific case of mask use, moreover, I think it is fairly easy to remember if masks were used once one remembers having met a person. I'm open to debate on this, and I'll leave this issue open in order to know other's opinions about the matter.

For now, if you have the need of storing if you or the people you were in contact with, I can recommend you to write it in the `Notes` section.

**Comment by smanz** [comment]
True, for most events it is easy to remember whether masks were used or not. I *do* have problems remembering this on reoccurring events like the weekly in-person meeting at work, or the small-talk with my neighbor. Was it last week or the week before when that person did not wear a mask while giving his presentation?
However, 1) those events are rare and 2) using the `Notes` section works fine for me. 

After I submitted the feature request, I realized that there is another reason for not asking for masks. The number of inputs per event should be as few as possible, even if the input is optional. The more choices you are confronted with, the less convenient is the user experience.

Maybe it is a good idea to keep this thread open for others to comment. From my point of view, however, I no longer request the feature.

**Comment by apozas** [comment]
> After I submitted the feature request, I realized that there is another reason for not asking for masks. The number of inputs per event should be as few as possible, even if the input is optional.

Indeed. I try to have this on my mind when thinking of new features. I see this app being, in a sense, altruistic. The primary reason you use it is because you want to protect others, not yourself. I have experienced going through uneasy processes in order to do altruistic acts, and it is very discouraging. Thus, my intention is to make the effort of filling the forms as small as possible. I am happy to see that we are on the same page. In any case, the issue will remain open for some time.

**Comment by apozas** [comment]
Regarding this topic, I'm having doubts on what information could be asked. Here are my thoughts so far:

- It is important that all members of an interaction wear masks, but asking _Did all members use masks?_ is only useful if the answer is Yes. If the answer is No, then the contact is more or less risky depending on whether it was you or if it was the rest not wearing it, since masks seem to be, primarily, for not transmitting the virus instead of for not getting it.
- I could ask two questions, _Did you wear a mask?_ and _Did the rest wear masks?_, but that may be a bit more boring to fill in.
- Also, I could choose to just ask _Did the rest wear masks?_, understanding that the user would remember if he/she wore it. But (1) some people will wonder (maybe fairly) that why asking one thing and not the other, and (2) the most important, if you test positive, is whether **you** used a mask or not.

By writing down these thoughts, I may have inclined more my thought into the idea that the most useful thing, in terms of notifying people you may have infected after knowing you have tested positive, is asking _Did you wear a mask?_. Also, this is probably what a contact tracer would need to know in order to assess the gravity of the contact.

Does anyone have any comments about this?

**Comment by smanz** [comment]
Well, there is the idea of backward cluster tracing (finding the super-spreading event in which a person was infected and then quarantine all participants of that event). This approach exploits the overdispersion characteristic of the virus. From what I have read, Japan was quite successful with this strategy. 
However, it is more important to know if **others** were wearing masks when searching for the super-spreading event.

Nevertheless, I still think input is getting to complicated for the user when additionally asking for masks.

An idea to deal with this would be to re-phrase the _did you keep distance_ question to something more generic like _were mitigation measures in place (e.g. distance, masks, ventilation)_.

This way the masks part (and other measures as well) would be covered by the more generic question.

**Comment by apozas** [comment]
> I still think input is getting to complicated for the user when additionally asking for masks.
I agree. As of `v1.3.0` there are no compulsory fields (except for the name), but I'm afraid that the very fact that the forms are longer will "scare" some people out.

> An idea to deal with this would be to re-phrase the did you keep distance question to something more generic like were mitigation measures in place (e.g. distance, masks, ventilation).
Well, this looks interesting as well. In fact, it's quite a good idea. Thanks!

**Comment by apozas** [comment]
For the next version, I changed the question _Did you kept the distance?_ by the more generic _Were preventive measures taken?_ (see [`7318cf9`](https://github.com/apozas/contactdiary/commit/7318cf92a4cb57fdd77599b67774a862c7c78f2e#diff-e00e29f1380e042f0692a615359518250a56256560ada594dd86ed05beef3125)). In case the term _preventive measures_ is not completely clear for everybody, I also [added a small button](https://github.com/apozas/contactdiary/commit/74e196cd42c81e0524d8c631f819b7237149d27c) next to the question, with a [short explanation](https://github.com/apozas/contactdiary/commit/74e196cd42c81e0524d8c631f819b7237149d27c#diff-e00e29f1380e042f0692a615359518250a56256560ada594dd86ed05beef3125). How does this look?

**Comment by smanz** [comment]
I like it. *thumbs up*

**Comment by apozas** [comment]
I really wonder why I did not think of this before!

<img src="https://user-images.githubusercontent.com/25796774/103478496-744d8480-4dc7-11eb-81d7-35d31e2bf6d6.jpeg" width="200" height="350"/>

Would this still be an interesting feature?

**Comment by smanz** [comment]
The problem I see here is that an empty checkbox can either mean that e.g. I did not wear a mask, or it can mean that I chose not to answer the question.

**Comment by apozas** [comment]
I think I can manage that. If the menu is open and "Accept" is clicked, the text in the form changes from "Click to select" to "None". I think it is fair to assume that, if one chooses not to answer the question, they will not go through the process of opening the menu -> selecting nothing -> click accept. Therefore it is possible to distinguish both cases (Selected no measures vs. chose not to answer), and record them accordingly. This is not being done in `v1.4.0`, but it will be available in `v1.4.1`.

**Comment by smanz** [comment]
> I think I can manage that. If the menu is open and "Accept" is clicked, the text in the form changes from "Click to select" to "None". I think it is fair to assume that, if one chooses not to answer the question, they will not go through the process of opening the menu -> selecting nothing -> click accept. Therefore it is possible to distinguish both cases (Selected no measures vs. chose not to answer), and record them accordingly. This is not being done in `v1.4.0`, but it will be available in `v1.4.1`.

Yes, that would do the trick.

I just realized that my previous comment didn't answer your question and might read less polite than I wanted it to be. My apologies.

As a matter of fact, I do believe that the _preventive measures_ part as it exists in version 1.3.3 has some room for improvement. When answering this item, I always felt it should read _where **appropriate** preventive measures taken_. But this requires that the user judges the situation. Actually, this might already be the case even without the "appropriate".

The proposed way is a significant improvement. It leaves few room for interpretation to the user and still records the relevant information for an assessment by a professional contact tracer. Very consistent with the spirit of the app so far.
The downside would be a slightly more complicated input procedure. But the complication only happens when you chose to input this information which is fair enough if you ask me.

**Comment by apozas** [comment]
Thank you for the feedback :) It's been a bit of a long journey, but I think now the feature is in a state that will please most. I'm proceeding to close the issue, but feel free to reopen it should anything else come up.

> I just realized that my previous comment didn't answer your question and might read less polite than I wanted it to be. My apologies.

Not at all. Conversations with you have been very constructive and productive. I very much appreciate the time you have spent on this. Thank you very much :D
