### ISSUE TITLE
Suffix breaks F-Droid autoupdate

### ISSUE THREAD

**Issue by licaon-kter** [apozas/contactdiary#2]
Ref: https://github.com/apozas/contactdiary/blob/master/android_app/app/build.gradle#L35

Ref: https://f-droid.org/wiki/index.php?title=com.apozas.contactdiary/lastbuild_6&oldid=280264

Ref: https://gitlab.com/fdroid/fdroidserver/-/issues/144

**Comment by apozas** [comment]
Thank you for the notification. The issue will be fixed in the next release (see https://github.com/apozas/contactdiary/commit/5c43e665fbed0e2a4a10952b4d7644910dbfb4ab). Therefore, if I understood right, compilation will succeed only if the release tag and the app version coincide, no matter if they have the suffix or not?

**Comment by licaon-kter** [comment]
Yes, suffix is kinda broken in certain scenarios.

**Comment by apozas** [comment]
Great. Thank you for the information. I'm closing the issue for now.

**Comment by apozas** [comment]
I am reopening this issue again because I have noticed that version `1.0.5-github`, corresponding to the Github tag [v1.0.5](https://github.com/apozas/contactdiary/releases/tag/v1.0.5), is now [building successfully](https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_6) and accordingly shown in [F-Droid](https://f-droid.org/en/packages/com.apozas.contactdiary/). Does this mean that I can keep using the suffix for denoting versions? Thank you very much.

**Comment by licaon-kter** [comment]
When I fix builds (see history https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/com.apozas.contactdiary.yml ) I open issues upstream too. ;)

But my fix is for that version only, in this case.

**Comment by apozas** [comment]
Understood. Thank you for your time. All versions starting next will not have any suffix.

**Comment by apozas** [comment]
Sorry for re-opening this again, but it seems like now the automated process is looking for versions with the suffix (https://f-droid.org/wiki/index.php?title=com.apozas.contactdiary/lastbuild_9). Is this something that can be solved from your side, or from now on I should keep the suffix? Thank you for your time and patience

**Comment by GenosseFlosse** [comment]
@licaon-kter Is there any possibility for the fdroid update process to stop looking for the suffix?

**Comment by licaon-kter** [comment]
@GenosseFlosse We can disable autoupdate until this is fixed, right.

**Comment by GenosseFlosse** [comment]
@licaon-kter What I meant is maybe removing the suffix in the autoupdater.

**Comment by licaon-kter** [comment]
The suffix is a gradle feature, we can't remove it selectively as other apps need this functionality.

**Comment by apozas** [comment]
I'm sorry, but I do not understand what I must do to have F-Droid building properly. Currently, the [build.gradle](https://github.com/apozas/contactdiary/blob/master/android_app/app/build.gradle#L14) contains no suffixes and the versionName coincides with the name of the release on GitHub. Is there anything that I should do different to F-Droid to be able to build? Thanks for your time.
