### ISSUE TITLE
[Bug] Crash when entering malformed hour:minute duration

### ISSUE THREAD

**Issue by bbastin** [apozas/contactdiary#21]
**Description of the bug**
The App crashes when the duration is a malformed hour:minute string

**To Reproduce**
1. Add new entry
2. Select duration field
3. Enter a malformed hour:minute duration like ”:30“ or ”1:“, or something non-numerical

**Expected behavior**
Either an error message or more lenient parsing which sets the hours/minutes to zero when they are missing or unparsable.

**Additional information**
App Version: 1.2.0
Android Version: 10

**Comment by apozas** [comment]
Hi,

Thanks for letting me know. Well, that's what happens when you don't follow the indications :stuck_out_tongue_closed_eyes:

Jokes aside, I tried to capture most "standard" mistakes when entering the form, and output a warning toast message. But as you have been able to check, these standard mistakes did not cover the cases you are mentioning.

The new version, [`1.3.0`](https://github.com/apozas/contactdiary/releases/tag/v1.3.0), removes the duration field (see https://github.com/apozas/contactdiary/commit/537a4ea15fac70fc796f12a18583979c4c414eb0) in favor of a time of begin and time of end. This new version successfully built on [F-Droid](https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_12) a few days ago, but for some reason I am not able to see it on the store yet. Hopefully, this will be solved in the next day or two.

Since this problem is solved (by making the duration disappear in `v1.3.0`), I'm closing the issue.
