### ISSUE TITLE
App doppelt Begegnungen aus 2020 nicht für 2021

### ISSUE THREAD

**Issue by pinguin121** [apozas/contactdiary#31]
Ich kann die Einträge aus dem alten Jahr nicht ins neue kopieren (z.B. meine Familie). Das Erstellen von neuen Kontaktbegegnungen geht grundsätzlich aber schon.

Ich nutze ein Fairphone 3, Android 10, die App-Version beziehe ich aus F-Droid und sie ist 1.3.2

**Comment by apozas** [comment]
(In Deutscher Sprache mit Hilfe von Google)
Hallo pinguin. Dieses Problem wurde bereits in #29 and #30 kommentiert, und in https://github.com/apozas/contactdiary/commit/9083927e264d5c2fb877b1e48c8d6bf8c12d2f66 behoben. Wenn Sie die Play Store-Version verwenden, funktioniert "Eintrag für heute kopieren" einwandfrei, wenn Sie auf Version `1.3.3` aktualisieren. Wenn Sie die App von F-Droid heruntergeladen haben, sollte dieses Update in den nächsten Tagen verfügbar sein. Zu diesem Zeitpunkt liegt es jedoch außerhalb meiner Kontrolle, wann genau das Update veröffentlicht wird. Ich werde das Problem schließen.


(In English, the preferred language for creating issues)
Hi pinguin. This issue has already been commented in #29 and #30, and fixed in https://github.com/apozas/contactdiary/commit/9083927e264d5c2fb877b1e48c8d6bf8c12d2f66. If you're using the Play Store version, "Make a copy today" will work fine if you upgrade to version `1.3.3`. If you've downloaded the app from F-Droid, this update should be available in the next few days, but at this point it is out of my control when precisely the update will roll out. I am proceeding to close the issue.
