### ISSUE TITLE
[Bug] When copy contact for today the year is set to 2020 instead of 2021

### ISSUE THREAD

**Issue by a123qwertz567** [apozas/contactdiary#32]
**Description of the bug**
When I use the feature "Copy contact for today" the year gets set to 2020 instead of 2021.

**To Reproduce**
Use the copy contact for today feature.

**Expected behavior**
Date should be with 2021 as year.

**Screenshots**
None for now

**System information (please complete the following information):**
 - Device: Moto G8 Power
 - Android version: 10
 - OS: Lineage OS Custom Build
 - App version: 1.3.2

**Additional context**
None for now

**Comment by apozas** [comment]
Hi a123qwertz567,

This issue has already been commented in #29, #30 and #31, and fixed in https://github.com/apozas/contactdiary/commit/9083927e264d5c2fb877b1e48c8d6bf8c12d2f66. If you're using the Play Store version, "Make a copy today" will work fine if you upgrade to version `1.3.3`. If you've downloaded the app from F-Droid, this update should be available in the next few hours ([the logs](https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_15) show that it was successfully built), but at this point it is out of my control when precisely the update will roll out. I am proceeding to close the issue.
