### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [apozas/contactdiary#39]
https://monitor.f-droid.org/builds/log/com.apozas.contactdiary/24#site-footer

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalGithubRelease'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintTask$AndroidLintLauncherWorkAction
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
         > Lint found fatal errors while assembling a release target.
```

Could you please take a look? Thanks!

**Comment by apozas** [comment]
Thanks for the pointer! It seems like the problem was a string that was deleted on the main `strings.xml` but not in the localization files. Hopefully https://github.com/apozas/contactdiary/commit/d57a5c02add986388f05c9fec3428649d8472999 will have done the job.

**Comment by linsui** [comment]
Thanks!

**Comment by apozas** [comment]
@linsui the issue was fixed, but it seems like F-Droid is not trying to build again. I found out that the app is now in the [needs updating](https://monitor.f-droid.org/builds/needsupdate) list, and I am afraid that that is what is preventing the build. I tried to edit the [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.apozas.contactdiary.yml) (namely removing L129 and replacing L130 by `commit: v1.4.7`) in order to bring all back to normal, but when I try to do so I consistently receive the following error:

> Someone edited the file the same time you did. Please check out the file and make sure your changes will not unintentionally remove theirs.

Given that it seems that you did the last update to the metadata file, would it be possible that you wrote the necessary changes into the file? Or shall I do something else in order to trigger the build process?

**Comment by igor-cali** [comment]
> Someone edited the file the same time you did. Please check out the file and make sure your changes will not unintentionally remove theirs.

@apozas please make sure your fork of the F-Droid metadata repo is synched to the master before editing the yml.

**Comment by linsui** [comment]
@apozas Sorry, I missed your comment. I didn't notice that you retag 1.4.7. I'll re-enable 1.4.7. Thanks!
