### ISSUE TITLE
Add duration of events and contacts

### ISSUE THREAD

**Issue by davidhelbig** [apozas/contactdiary#4]
Hi!
First, I really like the app and I really appreciate the time and effort that has been put into its development so far!

Regarding the tracking of time, I think it would be good to add an **end** time and separate it from the default start time of an event or contact. I think the duration is useful information for contact tracing in public spaces and it can be used as a factor in classifying the intensity of a contact.

**Comment by apozas** [comment]
Hi David,

Thank you. I am very happy knowing that you find the app useful :)

I have had some thoughts about this. Asking for more information about the contacts is a bit tricky. The premise I use is that it must be a professional contact tracer who assesses whether a contact is risky enough, instead of the individual using the app. Adding too much information about a contact may incline to self-evaluation of contacts, and to thoughts of "well, this contact doesn't seem of enough risk, so I won't tell the contact tracer". That is part of the reason why, right now, there is no question about mask use, for example.

That being said, it is true that it feels a bit weird to ask for a beginning time and not for an end time. Also, it is possible that knowing whether a meeting lasted 30 minutes or 2 hours is useful for the contact tracers to assess the risk in certain situations (although this is typically easy to remember once you remember the meeting happened, if you had forgotten). Finally, I have been asked for this a few times already. So I think I will add the contact end time.

**Comment by leso-kn** [comment]
I agree, contact ws

**Comment by leso-kn** [comment]
I agree, an end time field will be useful for sure!

If you have doubts that this will make people not log shorter events, maybe consider adding a check box or an alternative end value for 'short contact'.

I believe this option may even motivate to log short contacts

**Comment by apozas** [comment]
Don't think I have forgotten about this. I am still thinking about it ;)

I agree that just setting a beginning time is useless. In fact, now it is just used for ordering the table. But also, it is irrelevant to know _at which period of the day_ the contact occurred. What actually seems to matter is the _duration_ of the contact. I am thus now considering removing the Time field, and substituting it by a Duration field. Would you mind sharing your thoughts (if any) about this?

**Comment by leso-kn** [comment]
Yeah, I think that makes sense.

I guess knowing the exact time of a contact is only relevant in case you meet two or more people on the same day at different times and one of them is infected. _Then_ you may want to know whom of the other people you met before and whom after.

But in that case I believe it's very likely that you'll A: still remember who you met first without writing it down and/or B: just inform all people you met on that day.

**Comment by apozas** [comment]
Well, I was unexpectedly busy during these last weeks, but https://github.com/apozas/contactdiary/commit/b9603bb846b44b307feef3f7a018528a4cfd5282 and https://github.com/apozas/contactdiary/commit/3069e567eb48bf86c29cb614d56779c9a8bcf758 replace the query for time by a question about the duration of the contact. Any feedback is appreciated.

**Comment by leso-kn** [comment]
Sounds good! Looking forward to seeing it in the app

**Comment by matthias-vorwerk** [comment]
Hi,
thank you very much for this nice, useful app. It was what I was looking for.
The reason why I ended up in this discussion is the (now) missing start time. We discussed this in our family and feel that it is a missing information in some situations. The duration is important and should be kept. But having the possibility to **optionally** enter the start time would be quite important for us.
Not sure what others think about it.

**Comment by apozas** [comment]
Hi,

After playing a bit with the Duration feature, I admit that I myself also liked the way of entering times better. Therefore, in the next version I will come back to inserting times, with the ability to insert a beginning and an ending time. Also, no fields will be compulsory except for the name (the bare minimum). I have arrived to the realization that I/the app should not assume responsibilities on what the users input (see also the discussion in #14).
