### ISSUE TITLE
[Bug] The mobile phone number entered in incorrect format

### ISSUE THREAD

**Issue by jiaoqingqinggitee** [apozas/contactdiary#43]
The format of the entered mobile phone number is incorrect, there is no prompt, and it can be saved successfully
<img src=https://user-images.githubusercontent.com/84500440/139428516-de1405fc-d520-401a-baa1-9e635bfeee87.png width='200px' />

**Comment by apozas** [comment]
Hello, thanks for the notice.

In fact, there was a bit of thought at the beginning when I decided to put phone numbers. There are many phone number formats around the world, and there are different ways of inputting them. It is a fair bit of work to have all this into account, and I fear that once I do it there will be people coming to say that they are not able of inputting the phone number in the way they like. Therefore I'm inclined to leave this field as is, although I am open to be convinced otherwise.
