### ISSUE TITLE
Events and contact attributes not saved

### ISSUE THREAD

**Issue by diesendungmitdermaus** [apozas/contactdiary#5]
Hi!
The values "relative or close fried" - "yes", "encounter type" - "indoors" and "kept the distance" - "no" are not saved correctly with the event/contact. Instead, the values revert to "no", "outdoors" and [nothing].

Reproduce:
tap create a new contact
enter name, place, date. 
tap "yes", "indoors" and "no".
tap check mark icon to save
tap entry for the newly created contact in the list
-> values "no" and "outdoors" are selected, and nothing on the third question.

**Comment by apozas** [comment]
Hi,

Unfortunately I am not able to reproduce this issue. What device, Android version, and app version are you using? Thank you for your patience

**Comment by mziehm** [comment]
I having the same problem on two Devices: Samsung A41 running Android 10 and Honor 8 running Android 6. In both cases installed version 1.0.5-github from the F-Droid store.

I can add that selecting "no" and "ourdoors" will result in no visible selectiong on repoening the event.

Looks to me like a typical off by 1 problem (i.e. starting to count options from 0 or 1), since the display seems to be shifted by one from the selection.

Otherwise thanks for creating the app and I like the approach: simplicity and a few as possible permissions first and optional features later.

**Comment by igor-cali** [comment]
I also experience this with Android 8:
Huawei Honor 8 (FRD-L09)
Build: 8.0.0.521 (C432)

**Comment by apozas** [comment]
Hi,

Thanks a lot for the confirmations. I have seen that the issue is not present in earlier versions, so it should be easy to fix. I should have something ready within the next 24 hours.

**Comment by diesendungmitdermaus** [comment]
> Unfortunately I am not able to reproduce this issue. What device, Android version, and app version are you using? Thank you for your patience

Hi, sorry, I forgot:
Android 10, app Version is 1.0.5-github from f-droid

**Comment by hoschi-it** [comment]
I can also confirm this with Android 10 and app version 1.0.5

For better reproduction of the Problem, I have taken some screenshots. They show the edit view of entries that have been created and then shown in edit view. Description of the initial input values is in the persons name.

![00a604a3-0534-46e6-aa3c-a6e04ad84dc2](https://user-images.githubusercontent.com/20945369/96367608-30939900-114f-11eb-91f0-cc7d55fb42b1.png)
![9937ad2d-d061-4028-9a72-d25c5c1cd8c0](https://user-images.githubusercontent.com/20945369/96367622-41dca580-114f-11eb-96cb-77e16d4cb90b.png)
![21e986bb-d835-4934-91a7-a86adef3a117](https://user-images.githubusercontent.com/20945369/96367629-4c973a80-114f-11eb-95bc-7544658743ea.png)
![ad53c2a8-46fc-4ff8-86d7-f15b2b206481](https://user-images.githubusercontent.com/20945369/96367638-59b42980-114f-11eb-8c78-58a409ce8caa.png)
![e368941e-b27d-4730-9f49-2d5ca5052e9b](https://user-images.githubusercontent.com/20945369/96367646-62a4fb00-114f-11eb-8f69-e95857da004c.png)
![abdc8a2d-dc64-43e1-8dc4-4e6a971b52d6](https://user-images.githubusercontent.com/20945369/96367656-6b95cc80-114f-11eb-9ff0-7c494553e9f1.png)

**Comment by apozas** [comment]
The issue seems to be caused by https://github.com/apozas/contactdiary/commit/efada112eabdbd697b1c0f94714942208580ce9b. Using `Space` views instead of fixed lengths to separate the `RadioButton`s interferes with the indices stored in the database. https://github.com/apozas/contactdiary/commit/255c582909cc40ad25fe94dc2c980c534bba54ee should fix this. I'd kindly ask you to re-insert the questionnaires for your contacts after updating (make a copy of the information before updating, as the update _may_ be non-backwards compatible). I will make the release on Github in a few hours, that should be picked up by F-Droid in the coming days.

**Comment by apozas** [comment]
The new version [`v1.1.2`](https://github.com/apozas/contactdiary/releases/tag/v1.1.2) fixes the problem without requiring information loss. Please, if possible, skip `v1.1.1` and go directly to `v1.1.2`.

**Comment by hoschi-it** [comment]
> The new version [`v1.1.2`](https://github.com/apozas/contactdiary/releases/tag/v1.1.2) fixes the problem 

Thanks for the quick fix @apozas.
I can confirm it now works on my device.

**Comment by apozas** [comment]
I have realized that while v1.1.2 prevents the problem for new entries, it does not prevent it (yet) in entries created with older versions. In fact, there is no way of fixing perfectly the issue for entries generated in older versions, which may even crash the app. https://github.com/apozas/contactdiary/commit/d3507ea3088a3d41e19d7182b5e8ee53715a14fd provides a solution that attempts to do minimal impacts on the old entries. Any first or third `RadioButton` will be set accordingly, but any second one will display the first instead. The way of fixing this is, unfortunately, manually.

I apologize for the inconveniences. If you think you have found a solution to a problem just after waking up, first have a coffee and then start coding, not the other way around ^^U

**Comment by diesendungmitdermaus** [comment]
Hi, thank you for the quick response and also for the warning about the old items. I will wait for it appear via f-droid and update then.

**Comment by igor-cali** [comment]
@apozas please notice the build in f-droid fails: https://f-droid.org/wiki/index.php?title=com.apozas.contactdiary/lastbuild_9&redirect=no

**Comment by apozas** [comment]
Thank you for notifying. This has very likely to do with #2. I will re-open it to have it fixed

**Comment by diesendungmitdermaus** [comment]
Hi, I just got 1.1.3. via f-droid, and everything seems to bei working fine now. Thank you!
